### ISSUE TITLE
MISRA-C- Rule 16.3 

### ISSUE THREAD

**Issue by Mohamed-Obaid-QX** [humanoidSocialRobot/HumanoidSocialRobot_2024#7]
Rule 16.3 An unconditional break statement shall terminate every switch-clause.
Please add break; statement after every case {} and the default case in the main loop switch case 
https://github.com/humanoidSocialRobot/HumanoidSocialRobot_2024/blob/03b7df49fe787ef865e347f0edf898b7811d3695/Workspace_Humanoid/Humanoid_Blackbill2/Core/Src/main.c#L207

**Comment by yaramohali** [comment]
Switch case have been edited.
